In [7]:
import numpy as np
import pandas as pd
#pickle for model consistency 

In [ ]:
# LINEAR REGRESSION - CONTINUOUS DATA, SUPERVISED LEARNING 

sklearn.linear_model.LinearRegression(fit_intercept=True, normalize=False, copy_X=True, n_jobs =1)
#fit intercept = computes the intercept of the model 
#normalize = normalizes the regression variable before performing regression
#copy_X = copies the regression variable 
#n_jobs = number of jobs to use for the computation

In [8]:
from sklearn.datasets import load_boston
boston_dataset = load_boston()

In [9]:
print(boston_dataset['DESCR'])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [12]:
boston_dataset['feature_names']

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [13]:
df_Boston = pd.DataFrame(boston_dataset.data)

In [14]:
df_Boston.columns = boston_dataset.feature_names

In [15]:
df_Boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [16]:
boston_dataset.data.shape

(506, 13)

In [17]:
boston_dataset.target.shape

(506,)

In [18]:
df_Boston['Price'] = boston_dataset.target

In [19]:
df_Boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  Price  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [24]:
X_features = boston_dataset.data
Y_target = boston_dataset.target

In [25]:
from sklearn.linear_model import LinearRegression
linReg = LinearRegression()

In [26]:
linReg.fit(X_features, Y_target)

LinearRegression()

In [28]:
print('The estimated intercept is : %.2f' % linReg.intercept_)

The estimated intercept is : 36.46


In [32]:
print('The coefficient is : %.2f' % len(linReg.coef_))

The estimated coefficient is : 13.00


In [33]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X_features, Y_target)

In [34]:
print(boston_dataset.data.shape)

(506, 13)


In [35]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape )

(379, 13) (127, 13) (379,) (127,)


In [36]:
linReg.fit(x_train, y_train)

LinearRegression()

In [37]:
MSE = np.mean((linReg.predict(x_test)-y_test)**2)
print('The Mean Squared Error (MSE) is : %.2f' % MSE )

The Mean Squared Error (MSE) is : 23.52


In [38]:
#the variance represents accuracy, the closer to 1 the better 
print('The Variance is : %.2f' % linReg.score(x_test,y_test) )

The Variance is : 0.74


In [39]:
# LOGISTIC REGRESSION - CATEGORICAL DATA, SUPERVISED LEANRING

class sklearn.linear_model.LogisticRegression(penalty='l2', dual = 'False', tol=0.0001, C=1.0, fit_intercept= True, intercept_scaling=1, class_weight=None, random_state=None, solver='liblinear', max_iter=100, multi_class='ovr', verbose=0, warm_start=False, n_jobs=1)

multiclass => ovr = binomial 
penalty = norm in penalty
dual = only for L2 penalty

In [1]:
# K-NN (classification and regression)
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [2]:
type(iris_dataset)

sklearn.utils.Bunch

In [3]:
print(iris_dataset['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
iris_dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
iris_dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
iris_dataset.data.shape

(150, 4)

In [17]:
X_feature = iris_dataset.data
Y_target = iris_dataset.target

In [18]:
X_feature.shape, Y_target.shape

((150, 4), (150,))

In [19]:
from sklearn.neighbors import KNeighborsClassifier

In [20]:
knn = KNeighborsClassifier(n_neighbors =1)
print(knn)

KNeighborsClassifier(n_neighbors=1)


In [21]:
knn.fit(X_feature, Y_target)

KNeighborsClassifier(n_neighbors=1)

In [22]:
X_new = [[3,5,4,1], [5,3,4,2]]

In [23]:
knn.predict(X_new)

array([1, 1])

In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
logReg = LogisticRegression()

In [27]:
logReg.fit(X_feature, Y_target)

/Users/aina/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [28]:
logReg.predict(X_new)

array([0, 1])

In [29]:
# K-MEANS - CONTINUOUS DATA, UNSUPERVISED LEANRING

sklearn.cluster.KMeans(n_clusters=8, init='k_means++', n_init =10, max_iter=300, tol =0.0001, precompute_distances='auto', verbose=0,random_state=None, copy_x=True, n_jobs=1)

n_init = number of times kmeans will be run with different centroid seed
n_clusters = number of clusters to form and centroids to generate
random_state = initializes the center
copy_x =true does not modify the data during processing

In [31]:
from sklearn.cluster import KMeans

In [32]:
from sklearn.datasets import make_blobs

In [43]:
n_samples = 300
random_state = 20 # value to initialize the center
X,y = make_blobs(n_samples=n_samples, n_features=5,random_state=None)
predict_y = KMeans(n_clusters=3,random_state=random_state,max_iter=300).fit_predict(X)

In [44]:
X

array([[ -4.71585394,  -9.11027768,  -8.95751164,  -5.11009693,
          3.45014116],
       [ -2.93507602,  -9.65690027, -10.95031885,  -7.80325261,
          4.20301292],
       [  1.29277838,  -3.85225975,   0.11827209,   5.52182428,
         -7.18812098],
       ...,
       [ -6.84803529,   4.16750729,  -0.80923079,  -5.37197837,
         -7.81277425],
       [ -4.9456411 ,  -8.43453656,  -9.71300898,  -4.88107065,
          4.76903823],
       [ -8.4121791 ,   3.95338444,  -2.29051427,  -6.96366201,
         -9.16059769]])

In [45]:
y

array([2, 2, 1, 1, 1, 2, 2, 0, 2, 2, 0, 0, 2, 1, 1, 2, 2, 1, 1, 2, 1, 2,
       0, 1, 0, 0, 1, 0, 2, 1, 2, 0, 1, 1, 0, 1, 1, 0, 2, 1, 1, 2, 1, 2,
       0, 1, 2, 0, 2, 1, 1, 2, 2, 2, 0, 0, 1, 2, 0, 0, 1, 0, 2, 0, 0, 1,
       1, 2, 2, 0, 1, 2, 2, 1, 1, 0, 1, 2, 2, 1, 1, 2, 2, 2, 0, 1, 0, 0,
       0, 0, 1, 2, 1, 0, 2, 2, 0, 1, 1, 0, 1, 1, 0, 1, 2, 0, 2, 2, 0, 0,
       0, 1, 1, 0, 1, 1, 2, 1, 2, 2, 2, 0, 1, 1, 0, 0, 0, 0, 2, 0, 0, 2,
       0, 2, 2, 0, 0, 2, 0, 2, 0, 2, 2, 1, 0, 0, 2, 0, 0, 2, 2, 1, 1, 1,
       0, 2, 0, 2, 2, 0, 1, 2, 0, 2, 1, 2, 0, 1, 1, 1, 0, 2, 1, 0, 2, 1,
       0, 1, 1, 1, 2, 0, 1, 0, 1, 2, 1, 2, 0, 1, 2, 2, 1, 0, 1, 0, 0, 1,
       1, 1, 2, 1, 1, 0, 1, 1, 2, 1, 0, 1, 2, 0, 1, 2, 1, 0, 2, 0, 1, 0,
       0, 1, 2, 1, 0, 2, 2, 1, 1, 2, 1, 0, 0, 0, 2, 2, 0, 2, 2, 0, 2, 2,
       0, 0, 1, 1, 1, 2, 0, 0, 2, 0, 1, 2, 1, 0, 2, 1, 1, 0, 2, 2, 0, 1,
       2, 2, 2, 0, 2, 1, 0, 1, 0, 1, 2, 0, 2, 2, 1, 0, 1, 2, 1, 0, 1, 2,
       2, 1, 0, 1, 0, 0, 0, 0, 0, 2, 2, 0, 2, 0])

In [46]:
predict_y

array([1, 1, 0, 0, 0, 1, 1, 2, 1, 1, 2, 2, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       2, 0, 2, 2, 0, 2, 1, 0, 1, 2, 0, 0, 2, 0, 0, 2, 1, 0, 0, 1, 0, 1,
       2, 0, 1, 2, 1, 0, 0, 1, 1, 1, 2, 2, 0, 1, 2, 2, 0, 2, 1, 2, 2, 0,
       0, 1, 1, 2, 0, 1, 1, 0, 0, 2, 0, 1, 1, 0, 0, 1, 1, 1, 2, 0, 2, 2,
       2, 2, 0, 1, 0, 2, 1, 1, 2, 0, 0, 2, 0, 0, 2, 0, 1, 2, 1, 1, 2, 2,
       2, 0, 0, 2, 0, 0, 1, 0, 1, 1, 1, 2, 0, 0, 2, 2, 2, 2, 1, 2, 2, 1,
       2, 1, 1, 2, 2, 1, 2, 1, 2, 1, 1, 0, 2, 2, 1, 2, 2, 1, 1, 0, 0, 0,
       2, 1, 2, 1, 1, 2, 0, 1, 2, 1, 0, 1, 2, 0, 0, 0, 2, 1, 0, 2, 1, 0,
       2, 0, 0, 0, 1, 2, 0, 2, 0, 1, 0, 1, 2, 0, 1, 1, 0, 2, 0, 2, 2, 0,
       0, 0, 1, 0, 0, 2, 0, 0, 1, 0, 2, 0, 1, 2, 0, 1, 0, 2, 1, 2, 0, 2,
       2, 0, 1, 0, 2, 1, 1, 0, 0, 1, 0, 2, 2, 2, 1, 1, 2, 1, 1, 2, 1, 1,
       2, 2, 0, 0, 0, 1, 2, 2, 1, 2, 0, 1, 0, 2, 1, 0, 0, 2, 1, 1, 2, 0,
       1, 1, 1, 2, 1, 0, 2, 0, 2, 0, 1, 2, 1, 1, 0, 2, 0, 1, 0, 2, 0, 1,
       1, 0, 2, 0, 2, 2, 2, 2, 2, 1, 1, 2, 1, 2], d

In [47]:
# DIMESNIONALITY REDUCTION - PCA
# -dr0p data columns with low variance
# -PCA keeps highest variance 

sklearn.decomposition.PCA(n_components=None, copy=true, whiten=False)
n_components is elements to keep 

In [62]:
from sklearn.decomposition import PCA
from sklearn.datasets import make_blobs

In [63]:
n_sample = 20
random_state = 20

In [64]:
X,y = make_blobs(n_samples=n_samples, n_features=10,random_state=None)
X.shape

(300, 10)

In [65]:
pca = PCA(n_components=3)

In [66]:
pca.fit(X)
print(pca.explained_variance_ratio_)

[0.63593936 0.319894   0.00685526]


In [67]:
first_pca = pca.components_[0]
print(first_pca)

[-0.00274313  0.33715246 -0.01198225  0.09988975  0.22042223 -0.30011403
  0.65684808 -0.46369964  0.29502031 -0.06356901]


In [68]:
pca_reduced = pca.transform(X)
pca_reduced.shape

(300, 3)

In [69]:
#MODEL PIPELINES - to concat estimators
#all models need to be estimators except the last one, which can be a classifier

In [73]:
from sklearn.pipeline import Pipeline #Pipeline
from sklearn.linear_model import LinearRegression #Linear estimator
from sklearn.decomposition import PCA #estimator for dimensionality reduction

In [74]:
#put all models in a list
estimator = [('dim_reduction', PCA()), ('linear_model', LinearRegression())]

In [75]:
pipeline_estimator = Pipeline(estimator)

In [76]:
pipeline_estimator

Pipeline(steps=[('dim_reduction', PCA()), ('linear_model', LinearRegression())])

In [79]:
pipeline_estimator.steps[0], pipeline_estimator.steps[1]

(('dim_reduction', PCA()), ('linear_model', LinearRegression()))

In [80]:
# SAVING MODELS

In [85]:
iris_dataset.feature_names, iris_dataset.data, iris_dataset.target

(['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [

In [86]:
X_feature = iris_dataset.data
Y_target = iris_dataset.target
X_new = [[3,5,4,1], [5,3,4,2], [7,3,6,2]]
logReg.fit(X_feature, Y_target)
logReg.predict(X_new)

/Users/aina/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0, 1, 2])

In [87]:
import pickle as pkl

In [90]:
persist_model = pkl.dumps(logReg)
persist_model

b'\x80\x04\x952\x03\x00\x00\x00\x00\x00\x00\x8c\x1esklearn.linear_model._logistic\x94\x8c\x12LogisticRegression\x94\x93\x94)\x81\x94}\x94(\x8c\x07penalty\x94\x8c\x02l2\x94\x8c\x04dual\x94\x89\x8c\x03tol\x94G?\x1a6\xe2\xeb\x1cC-\x8c\x01C\x94G?\xf0\x00\x00\x00\x00\x00\x00\x8c\rfit_intercept\x94\x88\x8c\x11intercept_scaling\x94K\x01\x8c\x0cclass_weight\x94N\x8c\x0crandom_state\x94N\x8c\x06solver\x94\x8c\x05lbfgs\x94\x8c\x08max_iter\x94Kd\x8c\x0bmulti_class\x94\x8c\x04auto\x94\x8c\x07verbose\x94K\x00\x8c\nwarm_start\x94\x89\x8c\x06n_jobs\x94N\x8c\x08l1_ratio\x94N\x8c\x0en_features_in_\x94K\x04\x8c\x08classes_\x94\x8c\x15numpy.core.multiarray\x94\x8c\x0c_reconstruct\x94\x93\x94\x8c\x05numpy\x94\x8c\x07ndarray\x94\x93\x94K\x00\x85\x94C\x01b\x94\x87\x94R\x94(K\x01K\x03\x85\x94h\x1c\x8c\x05dtype\x94\x93\x94\x8c\x02i8\x94\x89\x88\x87\x94R\x94(K\x03\x8c\x01<\x94NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94b\x89C\x18\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x0

In [93]:
!pip install joblib
import joblib
joblib.dump(logReg, 'regresFilename.pkl')

['regresFilename.pkl']

In [94]:
new_logred_estimator = joblib.load('regresFilename.pkl')
new_logred_estimator.predict(X_new)

array([0, 1, 2])

#METRICS

Classification 
      metrics.accuracy_score, 
      metrics.average_precision_score
      
Clustering
      metrics.adjusted_rand_score
      
Regression
      metrics.mean_absolute_error, 
      metrics.mean_squared_error,
      metrics.median_absolute_error
